### ISSUE TITLE
use dc:title or rdfs:label for vocabs acdh:hasTitle

### ISSUE THREAD

**Issue by nczirjak-acdh** [acdh-oeaw/arche-schema-ingest#1]
at the moment the imported vocabs resources acdh:hasTitle is a url. f.e.: https://arche.acdh.oeaw.ac.at/browser/oeaw_detail/67340

But the vocabs metadata contains dc:title or rdfs:label, which has a normal text value and not an url :) Could you please change the vocabs ingesting code and use these properties for the acdh:hasTitle, instead of the url.

thanks!

**Comment by zozlak** [comment]
Implemented but you need to reingest the vocabulary for the changes to take place.
